### ISSUE TITLE
pennyphp.org domain expired

### ISSUE THREAD

**Issue by sasezaki** [pennyphp/pennyphp.github.com#6]
😢

**Comment by gianarb** [comment]
Yes and godaddy has in in trouble :) I am thinking to buy the .com but I don't know.. right know..
Sorry for this problem you can find all documentation here

https://github.com/pennyphp/penny/tree/master/docs

**Comment by gianarb** [comment]
thanks http://penny.gianarb.it/ :)

**Comment by sasezaki** [comment]
thanks for quick response 😄

**Comment by gianarb** [comment]
thank your for your ping
